apiVersion: skaffold/v2alpha3
kind: Config 
deploy:
  kubectl:
    manifests:
     - ./insfra/k8s/*
build:
  local: 
    push: false
  artifacts: 
    - image: attacktitan/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: attacktitan/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '**/*.js'
            dest: .